#!/usr/bin/env bash
# Configures my domain zone so that the subdomain www points to
# my load-balancer IP (lb-01), and my two servers IP (web-01 | web-02).

get_dns_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    destination=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" = 1 ]
then    
    sub_d=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${sub_d[@]}"
    do      
        get_dns_info "$1" "$sub_domain"
    done
         
elif [ "$#" = 2 ]
then
    get_dns_info "$1" "$2"
fi
