#!/usr/bin/env bash
# Installs Nginx to a Server with a redirection

sudo apt-get install -y nginx
sudo ufw allow 'Ngninx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me http://mwarstep.tech permanent;"
sudo sed -i "261 $line" /etc/nginx/sites-available/default
sudo service nginx restart
