#!/usr/bin/env bash
# Will install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y


# HAProxy Config
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server web-01 54.160.101.122:80 check
	server web-02 54.237.51.149:80 check
EOT

sudo /etc/init.d/haproxy start

# HAProxy will start on execution
sudo update-rc.d haproxy defaults

# HAProxy config reload
sudo /etc/init.d/haproxy reload
