#!/usr/bin/env bash
# Generates a MYSQL Dump and creates a compressed archive out of it

sudo mysqldump --all-databases -u root -p"$1" > backup.sql
sudo tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
