#!/usr/bin/env bash
# This generates a MYSQL Dump and creates a compressed archive out of it

sudo mysqldump --all-databases -u root -p"$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
