#!/usr/bin/env bash
# This debugs Nginx and configures the server to activate Nginx on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
