#!/usr/bin/env bash
# Will Loop for 1 to 10 using while loop and if, elif and else statements

x=1

while [ $x -le 10 ]
do
   if [ $x -eq 4 ]
   then
	echo "bad luck"
   elif [ $x -eq 8 ]
   then
	echo "good luck"
   else
	echo "Best School"
   fi
   ((x++))
done
